# 1st Docker build stage: build the project with Maven

FROM maven:3.8.4-eclipse-temurin-17-alpine as builder

WORKDIR /project
COPY . /project/
RUN mvn package -DskipTests -B

# 2nd Docker build stage: copy builder output and configure entry point

FROM eclipse-temurin:17-jre-alpine

ENV APP_DIR /application
ENV APP_FILE container-jar.jar

EXPOSE 8080

WORKDIR $APP_DIR
COPY --from=builder /project/target/*.jar $APP_DIR/$APP_FILE

ENTRYPOINT ["sh", "-c"]
CMD ["exec java -jar $APP_FILE"]

